let photos={}, signatures={engineer:null,customer:null}, editingIndex=null;
const $=id=>document.getElementById(id);
const photoItems=[['frontProperty','🏡 Front of Property'],['outdoorUnit','❄️ Outdoor Unit'],['serialPlate','🏷️ Serial/Data Plate'],['plantRoom','🔥 Indoor Unit / Plant Room'],['cylinder','🚰 Cylinder'],['controller','📟 Controller Screen'],['electrical','⚡ Electrical / Isolator']];
const workflows={
'Firebird|Commissioning':{title:'Firebird Commissioning & Warranty Workflow',note:'Manufacturer-style commissioning workflow based on Firebird Enviroair form structure.',sections:[
['Installation Details',['Heat pump installed to manufacturer instructions','Heat pump fixed on solid and level surface','Minimum clearances provided','Maintenance access from all sides and above','Free passage of air around heat pump','Flow and return pipes identified correctly','External pipework insulated','Full bore isolation valves fitted','Condensate trap and safe drainage fitted']],
['Electrical / External',['Physical protection of electrical wiring','Electrical separation of power and control wiring','Ingress protection IP65 or better','Suitable circuit breaker and cable size','Electrical installation complies with local building regulations']],
['Water Quality / Hydraulics',['System flushed and cleaned','System filtration fitted','Corrosion inhibitor added','Glycol manufacturer/type recorded','Glycol measured protection recorded','Bypass valve installed and set correctly','System filled and vented with all valves open']],
['Controller / DHW',['Time and date setup','DHW temperature setting recorded','3 port valve fitted and operating correctly','Cylinder filled with domestic water','Anti-legionella status recorded','Immersion controlled correctly']],
['Heating Settings',['Number of heating zones recorded','Heat emitter type recorded','Max flow temperature recorded','Lowest flow temperature recorded','Design external temperature recorded','Weather compensation setup and turned on','Flow and return temperatures recorded']],
['Customer Handover',['All air removed from system','Bypass adjusted','Radiators heat tested and operating','Operation and controls left with customer','Manufacturer literature left with customer']]]},
'Joule / Kodiak|Warranty Validation':{title:'Joule / Kodiak Warranty Validation',note:'Warranty validation workflow for Kodiak & Air Source Heat Pump.',sections:[
['Hydraulics',['Check pipework insulation','Check for signs of water leakage','Check inhibitor concentration level','Clean the line strainer','Remove trapped air','Check pressure set to 1.5 bar cold','Check heat emitters are balanced']],
['Electrical / Safety',['Check thermostat connections','Check thermostat functionality','Check heating safety','Check / charge expansion vessel']],
['Outdoor Unit',['Check for undue noise or vibration','Inspect for damage and clean','Inspect for corrosion','Inspect evaporator and clean fins','Inspect fan blade and motor','Clean condensate drainage','Check hydraulic flow and return temperatures','Check evaporator temperature','Check sensors are correctly inserted']],
['Cylinder',['Check controller for errors','Check cylinder for defects','Check system water pressure','Check outlet temperature','Check electrical wiring','Check high limit cut-outs','Clean inlet group line strainer','Check T&PR and expansion valves','Check tundish drains correctly']]]},
'Hitachi|Annual Service':{title:'Hitachi Annual Service Workflow',note:'Hitachi-style service request workflow.',sections:[
['Mechanical Tasks',['Maintenance access from all sides and above','Free passage of air around heat pump','Heat pump fixed on solid surface','Outdoor coil/fins inspected and cleaned','Oil/refrigerant leak visual check','Pipework and lagging checked','System operation checked','Antifreeze concentration checked','Inhibitor concentration checked','Particle filter cleaned','Expansion vessel checked','System pressure checked','Air released','Voltage above 220V checked','Vibration and sound checked']],
['Controller Tasks',['Thermostat operation checked','Zone valve operation checked','Immersion heater operation checked','Controller alarm history checked','Commissioning parameters checked','Heating handover pack onsite']]]},
'Mitsubishi Electric|Annual Service':{title:'Mitsubishi Ecodan Annual Service',note:'Ecodan annual service workflow foundation.',sections:[
['Outdoor Unit',['Visual inspection','Electrical connections checked','Plumbing/insulation checked','Unit cleaned of debris','Evaporator coil cleaned','Evaporator fins straightened if required','Compressor function test recorded']],
['Indoor Unit',['Visual inspection','Electrical connections checked','Strainer cleaned','Magnetic filter cleaned','Sensor position checked','Booster heater tested','Three-way valve tested','Air removed','Controller recommissioned']],
['Controls / Energy',['Thermostatic function checked','Motorized valves checked','Energy monitoring recorded','COP reviewed','Compressor run time and starts recorded']]]},
'Panasonic Aquarea|Annual Service':{title:'Panasonic Aquarea Annual Service',note:'Panasonic service workflow foundation.',sections:[['Service Checks',['Visual inspection completed','Y-strainer checked / cleaned','Magnetic filter checked / cleaned','Flow rate checked','Expansion vessel checked','Safety valve checked','Outdoor coil inspected','Controller settings checked','DHW operation checked','Backup heater checked','Error history checked']]]}
};
function jobs(){return JSON.parse(localStorage.hpJobs||'[]')} function setJobs(x){localStorage.hpJobs=JSON.stringify(x)}
function ppid(j){let s=(j.serial||j.customer||j.jobNo||'HPP');let h=Math.abs(s.split('').reduce((a,c)=>((a<<5)-a+c.charCodeAt(0))|0,0));return 'HPP-'+String(h).slice(0,6).padStart(6,'0')}
function go(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$(id).classList.add('active');scrollTo(0,0);render();setTimeout(initSig,100)}
function step(n,btn){document.querySelectorAll('.jobStep').forEach(s=>s.classList.remove('active'));$('s'+n).classList.add('active');document.querySelectorAll('.pill').forEach(p=>p.classList.remove('active')); if(btn)btn.classList.add('active'); else {let p=document.querySelectorAll('.pill')[n-1]; if(p)p.classList.add('active')}$('progressText').textContent='Step '+n+' of 7';$('progressBar').style.width=(n*14.28)+'%';scrollTo(0,0); if(n==4)renderWorkflow(); if(n==5)renderPhotos(); if(n==6)setTimeout(initSig,100); if(n==7)completion()}
function newJob(){editingIndex=null;photos={};signatures={engineer:null,customer:null};document.querySelectorAll('input,textarea').forEach(e=>{if(e.type!='file')e.value=''});$('engineer').value='Jeffrey Griffin';$('jobTitle').textContent='New Job';health();go('job');step(1);renderWorkflow();renderPhotos()}
function wf(){return workflows[$('maker').value+'|'+$('type').value]||workflows[$('maker').value+'|Annual Service']}
function renderWorkflow(){let w=wf(); if(!w){$('workflowTitle').textContent='Generic Workflow';$('workflowNote').textContent='Select manufacturer and job type.';$('workflow').innerHTML=sectionHtml(['Generic Checks',['Visual inspection','Filter cleaned','System pressure checked','Electrical checks','Controls checked']],0);return}$('workflowTitle').textContent=w.title;$('workflowNote').textContent=w.note;$('workflow').innerHTML=w.sections.map((s,i)=>sectionHtml(s,i)).join('')}
function sectionHtml(s,si){return `<div class="workflowSection"><h4>${s[0]}</h4>${s[1].map((item,ii)=>`<div class="checkRow"><div><b>${item}</b><input class="comment" data-key="${si}-${ii}" placeholder="Comment / value if required"></div><select class="mcheck" data-key="${si}-${ii}"><option>Not checked</option><option>Yes / Good</option><option>No / Requires Attention</option><option>N/A / NV</option></select></div>`).join('')}</div>`}
function renderPhotos(){$('photos').innerHTML=photoItems.map(([k,l])=>`<div class="photoBox"><b>${l} ${photos[k]?'✅':'⚪'}</b><input type="file" accept="image/*" capture="environment" onchange="savePhoto(event,'${k}')"><img ${photos[k]?`src="${photos[k]}" style="display:block"`:''}></div>`).join('')}
function savePhoto(e,k){let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=ev=>{let im=new Image();im.onload=()=>{let m=900,w=im.width,h=im.height;if(w>h&&w>m){h=Math.round(h*m/w);w=m}if(h>=w&&h>m){w=Math.round(w*m/h);h=m}let c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(im,0,0,w,h);photos[k]=c.toDataURL('image/jpeg',0.55);renderPhotos()};im.src=ev.target.result};r.readAsDataURL(f)}
function initCanvas(c,type){if(!c||c.dataset.ready)return;c.dataset.ready=1;let x=c.getContext('2d'),d=false;function resize(){let r=c.getBoundingClientRect(),old=signatures[type];c.width=r.width*devicePixelRatio;c.height=r.height*devicePixelRatio;x.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);x.lineWidth=3;x.lineCap='round';x.strokeStyle='#0f172a';x.fillStyle='#fff';x.fillRect(0,0,r.width,r.height);if(old){let im=new Image();im.onload=()=>x.drawImage(im,0,0,r.width,r.height);im.src=old}}function pt(e){let r=c.getBoundingClientRect(),t=e.touches?e.touches[0]:e;return{x:t.clientX-r.left,y:t.clientY-r.top}}function st(e){e.preventDefault();d=true;let p=pt(e);x.beginPath();x.moveTo(p.x,p.y)}function mv(e){if(!d)return;e.preventDefault();let p=pt(e);x.lineTo(p.x,p.y);x.stroke();signatures[type]=c.toDataURL('image/png')}function en(){d=false}c.addEventListener('mousedown',st);c.addEventListener('mousemove',mv);addEventListener('mouseup',en);c.addEventListener('touchstart',st,{passive:false});c.addEventListener('touchmove',mv,{passive:false});c.addEventListener('touchend',en);resize()}
function initSig(){initCanvas($('engineerCanvas'),'engineer');initCanvas($('customerCanvas'),'customer')} function clearSig(t){signatures[t]=null;let c=$(t+'Canvas');if(c){let x=c.getContext('2d'),r=c.getBoundingClientRect();x.fillStyle='#fff';x.fillRect(0,0,r.width,r.height)}}
function health(){let f=parseFloat($('flowTemp').value),r=parseFloat($('returnTemp').value),p=parseFloat($('pressure').value),rate=parseFloat($('flowRate').value),m=[];if(!isNaN(f)&&!isNaN(r)){let dt=f-r;$('deltaT').value=dt.toFixed(1);m.push(dt>=3&&dt<=7?'✅ Delta T looks good':dt<3?'⚠️ Delta T low - check flow rate or heat transfer':'⚠️ Delta T high - check flow rate or restrictions')}else $('deltaT').value='';if(!isNaN(p))m.push(p>=1&&p<=2.5?'✅ Pressure acceptable':'⚠️ Pressure needs checking');if(!isNaN(rate))m.push(rate>=10?'✅ Flow rate recorded':'⚠️ Low flow rate');$('healthBox').innerHTML=m.length?'System Health:<br>'+m.join('<br>'):'System Health: Enter readings'}
function collect(){return[...document.querySelectorAll('.mcheck')].map(s=>({status:s.value,comment:document.querySelector(`.comment[data-key="${s.dataset.key}"]`)?.value||''}))}
function data(){let j={jobNo:editingIndex==null?'HP-'+String(jobs().length+1).padStart(4,'0'):jobs()[editingIndex].jobNo,customer:$('customer').value,address:$('address').value,county:$('county').value,eircode:$('eircode').value,contact:$('contact').value,type:$('type').value,status:$('status').value,maker:$('maker').value,model:$('model').value,serial:$('serial').value,cylinderModel:$('cylinderModel').value,cylinderSerial:$('cylinderSerial').value,installDate:$('installDate').value,installer:$('installer').value,engineer:$('engineer').value,outdoorTemp:$('outdoorTemp').value,flowTemp:$('flowTemp').value,returnTemp:$('returnTemp').value,deltaT:$('deltaT').value,hotWaterTemp:$('hotWaterTemp').value,pressure:$('pressure').value,flowRate:$('flowRate').value,voltage:$('voltage').value,amps:$('amps').value,health:$('healthBox').innerText,photos,signatures,faults:$('faults').value,notes:$('notes').value,workflowName:$('workflowTitle').textContent,workflow:collect(),date:new Date().toLocaleString()};j.passportId=ppid(j);return j}
function completion(){let total=[!!$('customer').value&&!!$('address').value,!!$('maker').value&&!!$('model').value&&!!$('serial').value,!!$('flowTemp').value&&!!$('returnTemp').value&&!!$('pressure').value,[...document.querySelectorAll('.mcheck')].filter(x=>x.value!='Not checked').length>3,photos.outdoorUnit&&photos.serialPlate,!!signatures.engineer,!!signatures.customer];let names=['Customer details','Equipment details','Readings','Manufacturer workflow','Required photos','Engineer signature','Customer signature'];let score=Math.round(total.filter(Boolean).length/total.length*100);$('completion').innerHTML='Overall Completion: '+score+'%<br><br>'+names.map((n,i)=>(total[i]?'✅ ':'❌ ')+n).join('<br>')}
function saveJob(){let j=data(),l=jobs();j.status='Completed'; if(editingIndex==null)l.push(j);else l[editingIndex]=j;setJobs(l);alert('Saved. Passport updated: '+j.passportId);go('home')}
function render(){let l=jobs();$('totalJobs').textContent=l.length;$('totalCustomers').textContent=[...new Set(l.map(j=>j.customer).filter(Boolean))].length;$('totalPassports').textContent=[...new Set(l.map(j=>j.passportId||ppid(j)))].length;$('awaitingParts').textContent=l.filter(j=>j.status=='Awaiting Parts').length;$('recentJobs').innerHTML=l.length?l.slice().reverse().map((j,ri)=>`<p><b>${j.jobNo} - ${j.customer||'Unnamed'}</b><br>${j.maker} • ${j.model||'No model'}<br>${j.type} • ${j.date}<br><span class="badge">${j.passportId||ppid(j)}</span></p>`).join(''):'No jobs saved yet.';$('passportList').innerHTML=l.length?l.map(j=>`<p><b>${j.passportId||ppid(j)}</b><br>${j.maker} ${j.model||''}<br>${j.customer||''}<br>Serial: ${j.serial||'Not recorded'}</p>`).join(''):'No passports yet.'}
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function report(title,plain){let j=data(),rows=(j.workflow||[]).map((w,i)=>`<tr><td>${i+1}</td><td>${esc(w.status)}</td><td>${esc(w.comment)}</td></tr>`).join(''),imgs=Object.entries(j.photos||{}).map(([k,v])=>`<div><h4>${k}</h4><img src="${v}"></div>`).join('');let html=`<!doctype html><html><head><meta charset="utf-8"><title>${title}</title><style>body{font-family:${plain?'Times New Roman':'Arial'};margin:0}.r{max-width:900px;margin:auto;padding:26px}.h{${plain?'border:1px solid #111':'background:#0b6efd;color:white;border-radius:18px'};padding:18px}.b{border:1px solid #999;margin:12px 0;padding:12px}table{width:100%;border-collapse:collapse}td,th{border:1px solid #999;padding:7px}.photos{display:grid;grid-template-columns:1fr 1fr;gap:12px}.photos img{width:100%;max-height:260px;object-fit:cover}.sig{height:100px;border:1px solid #999}.sig img{max-height:95px;max-width:100%}@media print{.b{break-inside:avoid}}</style></head><body><div class="r"><div class="h"><h1>${title}</h1><p>${esc(j.maker)} • ${esc(j.type)} • ${esc(j.passportId)}</p></div><div class="b"><h2>Customer</h2><p>${esc(j.customer)}<br>${esc(j.address)}<br>${esc(j.eircode)}</p></div><div class="b"><h2>Equipment</h2><p>${esc(j.maker)} ${esc(j.model)}<br>Serial: ${esc(j.serial)}<br>Cylinder: ${esc(j.cylinderModel)} ${esc(j.cylinderSerial)}</p></div><div class="b"><h2>Readings</h2><p>Flow ${esc(j.flowTemp)}°C / Return ${esc(j.returnTemp)}°C / Delta T ${esc(j.deltaT)}°C / Pressure ${esc(j.pressure)} bar</p></div><div class="b"><h2>${esc(j.workflowName)}</h2><table><tr><th>#</th><th>Status</th><th>Comment</th></tr>${rows}</table></div><div class="b"><h2>Photos</h2><div class="photos">${imgs}</div></div><div class="b"><h2>Signatures</h2><p>Engineer</p><div class="sig">${j.signatures.engineer?`<img src="${j.signatures.engineer}">`:''}</div><p>Customer</p><div class="sig">${j.signatures.customer?`<img src="${j.signatures.customer}">`:''}</div></div></div><script>window.onload=()=>setTimeout(()=>print(),500)<\/script></body></html>`;let w=window.open('','_blank');if(!w){alert('Allow popups');return}w.document.write(html);w.document.close()}
function manufacturerReport(){report(($('maker').value||'Manufacturer')+' '+($('type').value||'')+' Report',true)} function proReport(){report('HeatPump Pro Professional Report',false)}
render();renderWorkflow();renderPhotos();setTimeout(initSig,300);