import { PlatformModuleDefinition } from '../../types/platform-modules';

const comingSoonRoute = (module: string) => `/coming-soon?module=${encodeURIComponent(module)}`;

export const platformModuleRegistry: PlatformModuleDefinition[] = [
  {
    key: 'installations',
    name: 'Installations',
    route: '/installations',
    iconKey: 'installations',
    description: 'View and manage installation records.',
    enabled: true,
    comingSoon: false,
    category: 'installations',
  },
  {
    key: 'service-visits',
    name: 'Service Visits',
    route: '/service',
    iconKey: 'service',
    description: 'Start and manage service workflows.',
    enabled: true,
    comingSoon: false,
    category: 'service',
  },
  {
    key: 'commissioning',
    name: 'Commissioning',
    route: '/commissioning-wizard',
    iconKey: 'commissioning',
    description: 'Commissioning workflow and records.',
    enabled: true,
    comingSoon: false,
    category: 'commissioning',
  },
  {
    key: 'fault-finder',
    name: 'Fault Finder',
    route: '/fault-finder',
    iconKey: 'fault',
    description: 'Diagnostic support for field engineers.',
    enabled: true,
    comingSoon: false,
    category: 'diagnostics',
  },
  {
    key: 'performance-analysis',
    name: 'Performance Analysis',
    route: comingSoonRoute('Performance Analysis'),
    iconKey: 'performance',
    description: 'Trend and performance insights.',
    enabled: false,
    comingSoon: true,
    category: 'diagnostics',
  },
  {
    key: 'reports',
    name: 'Reports',
    route: '/reports',
    iconKey: 'reports',
    description: 'Service and commissioning reports.',
    enabled: true,
    comingSoon: false,
    category: 'reports',
  },
  {
    key: 'equipment-knowledge-base',
    name: 'Equipment Knowledge Base',
    route: '/equipment-hub',
    iconKey: 'knowledge',
    description: 'Model catalogue and engineering references.',
    enabled: true,
    comingSoon: false,
    category: 'diagnostics',
  },
  {
    key: 'customers',
    name: 'Customers',
    route: '/customers',
    iconKey: 'customers',
    description: 'Customer records and engagement history.',
    enabled: true,
    comingSoon: false,
    category: 'business',
  },
  {
    key: 'parts-stock',
    name: 'Parts and Stock',
    route: comingSoonRoute('Parts and Stock'),
    iconKey: 'parts',
    description: 'Parts inventory and usage tracking.',
    enabled: false,
    comingSoon: true,
    category: 'business',
  },
  {
    key: 'fgas-records',
    name: 'F-Gas Records',
    route: comingSoonRoute('F-Gas Records'),
    iconKey: 'fgas',
    description: 'Refrigerant compliance records.',
    enabled: false,
    comingSoon: true,
    category: 'business',
  },
  {
    key: 'team-management',
    name: 'Team Management',
    route: comingSoonRoute('Team Management'),
    iconKey: 'team',
    description: 'Engineer roles, teams, and assignments.',
    enabled: false,
    comingSoon: true,
    category: 'business',
    requiredRole: 'manager',
  },
  {
    key: 'customer-portal',
    name: 'Customer Portal',
    route: comingSoonRoute('Customer Portal'),
    iconKey: 'portal',
    description: 'Customer-facing report and status portal.',
    enabled: false,
    comingSoon: true,
    category: 'business',
  },
];

export const modulesByCategory = (category: PlatformModuleDefinition['category']) =>
  platformModuleRegistry.filter((module) => module.category === category);
